version: '3.5'

services:
  Targeted:
    image: 'targeted_httpd'
    container_name: Targeted
    tty: true
    stdin_open: true
    #command: bash
    restart: always
    networks:
      - Cnet
      - docker-elk_elk
    ports:
      - "80:80"

  Attacker:
    image: 'attacker_kali-xrdp'
    container_name: Attacker
    tty: true
    stdin_open: true
    #command: bash
    privileged: true
    restart: always
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    ports:
      - "3389:3389"
      - "22:222"
    working_dir: /
    volumes:
      - /dev/net:/dev/net:z
      - ./data:/data
    networks:
      - Cnet
networks:
  Cnet:
    driver: bridge
  docker-elk_elk:
    external: true
