version: '3.5'

services:
  targeter:
    image: 'targeter'
    container_name: targeter
    tty: true
    stdin_open: true
    command: bash
    networks:
      - Cnet
      - docker-elk_elk
    ports:
      - "80:8080"

  attacker:
    image: 'attacker'
    container_name: attacker
    tty: true
    stdin_open: true
    command: bash
    privileged: true
    cap_add:
      - net_admin
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    ports:
      - "3389:3389"
      - "2222:22"
    working_dir: /
    volumes:
      - /dev/net:/dev/net:z
      - ./data:/data
    networks:
      - Cnet
networks:
  Cnet:
    driver: bridge
  docker-elk_elk:
    external: true
