version: '3.5'

services:
  targeter:
    image: 'targeter'
    container_name: targeter
    tty: true
    stdin_open: true
    command: bash
    networks:
      - Cnet
      - docker-elk_elk
    ports:
      - "80:8080"

  attacker:
    image: 'attacker'
    container_name: attacker
    tty: true
    stdin_open: true
    command: bash
    networks:
      - Cnet
networks:
  Cnet:
    driver: bridge
  docker-elk_elk:
    external: true
